spring:
  application:
    name: allgomath
  # Redis 설정 추가
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # 캐시 설정 추가
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1시간


#임시 비활성화
management:
  health:
    redis:
      enabled: true

  simple:
    metrics:
      export:
        enabled: true

  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health, metrics, info, caches


#logging

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
    com.yy.algorithm.fractal: DEBUG
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
